### ISSUE TITLE
string join operation on class TemplateKey fails

### ISSUE THREAD

**Issue by Gnork** [curious-containers/curious-containers#55]
If a `{{template_key}}` is sent to the `red` endpoint of CC-Agency, it results in a 500 error, because there is a string join operation, that involves TemplateKey instead of string.

```
Sep 27 17:15:08 agency uwsgi[24814]: Traceback (most recent call last):
Sep 27 17:15:08 agency uwsgi[24814]:   File "/home/cc/ccagency-venv/lib/python3.5/site-packages/flask/app.py", line 2446, in wsgi_app
Sep 27 17:15:08 agency uwsgi[24814]:     response = self.full_dispatch_request()
Sep 27 17:15:08 agency uwsgi[24814]:   File "/home/cc/ccagency-venv/lib/python3.5/site-packages/flask/app.py", line 1951, in full_dispatch_request
Sep 27 17:15:08 agency uwsgi[24814]:     rv = self.handle_user_exception(e)
Sep 27 17:15:08 agency uwsgi[24814]:   File "/home/cc/ccagency-venv/lib/python3.5/site-packages/flask/app.py", line 1820, in handle_user_exception
Sep 27 17:15:08 agency uwsgi[24814]:     reraise(exc_type, exc_value, tb)
Sep 27 17:15:08 agency uwsgi[24814]:   File "/home/cc/ccagency-venv/lib/python3.5/site-packages/flask/_compat.py", line 39, in reraise
Sep 27 17:15:08 agency uwsgi[24814]:     raise value
Sep 27 17:15:08 agency uwsgi[24814]:   File "/home/cc/ccagency-venv/lib/python3.5/site-packages/flask/app.py", line 1949, in full_dispatch_request
Sep 27 17:15:08 agency uwsgi[24814]:     rv = self.dispatch_request()
Sep 27 17:15:08 agency uwsgi[24814]:   File "/home/cc/ccagency-venv/lib/python3.5/site-packages/flask/app.py", line 1935, in dispatch_request
Sep 27 17:15:08 agency uwsgi[24814]:     return self.view_functions[rule.endpoint](**req.view_args)
Sep 27 17:15:08 agency uwsgi[24814]:   File "/home/cc/ccagency-venv/lib/python3.5/site-packages/cc_agency/broker/routes/red.py", line 109, in post_red
Sep 27 17:15:08 agency uwsgi[24814]:     ' to agency. Consider using CC-FAICE (faice exec).'.format(', '.join(template_keys)))
Sep 27 17:15:08 agency uwsgi[24814]: TypeError: sequence item 0: expected str instance, TemplateKey found
```

**Comment by Bluemi** [comment]
Fixed in [f11f057](https://github.com/curious-containers/cc-agency/commit/f11f057f496a5a05ced19e31e853235082d7e2ca)
