### ISSUE TITLE
node self-repair in check_exited_containers not working

### ISSUE THREAD

**Issue by Gnork** [curious-containers/curious-containers#57]
The connection from CC-Agency to the docker-engine on a compute node broke. This should trigger the following cascade:

* exception catched
* node inspection
* set node offline if inspection fails
* the node can then self-repair in future inspections where new client connections are established

As can be seen in the traceback from journalctl -u ccagency-controller, in the `_check_exited_containers` connection errors are not catched and therefore a node inspection is not triggered.

```
Traceback (most recent call last):
Oct 02 09:04:24 agency ccagency-controller[1314]:   File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
Oct 02 09:04:24 agency ccagency-controller[1314]:     self.run()
Oct 02 09:04:24 agency ccagency-controller[1314]:   File "/usr/lib/python3.5/threading.py", line 862, in run
Oct 02 09:04:24 agency ccagency-controller[1314]:     self._target(*self._args, **self._kwargs)
Oct 02 09:04:24 agency ccagency-controller[1314]:   File "/home/cc/ccagency-venv/lib/python3.5/site-packages/cc_agency/controller/docker.py", line 456, in _check_exited_containers_loop
Oct 02 09:04:24 agency ccagency-controller[1314]:     resources_freed = self._check_exited_containers()
Oct 02 09:04:24 agency ccagency-controller[1314]:   File "/home/cc/ccagency-venv/lib/python3.5/site-packages/cc_agency/controller/docker.py", line 438, in _check_exited_containers
Oct 02 09:04:24 agency ccagency-controller[1314]:     exited_container.remove()
Oct 02 09:04:24 agency ccagency-controller[1314]:   File "/home/cc/ccagency-venv/lib/python3.5/site-packages/docker/models/containers.py", line 339, in remove
Oct 02 09:04:24 agency ccagency-controller[1314]:     return self.client.api.remove_container(self.id, **kwargs)
Oct 02 09:04:24 agency ccagency-controller[1314]:   File "/home/cc/ccagency-venv/lib/python3.5/site-packages/docker/utils/decorators.py", line 19, in wrapped
Oct 02 09:04:24 agency ccagency-controller[1314]:     return f(self, resource_id, *args, **kwargs)
Oct 02 09:04:24 agency ccagency-controller[1314]:   File "/home/cc/ccagency-venv/lib/python3.5/site-packages/docker/api/container.py", line 990, in remove_container
Oct 02 09:04:24 agency ccagency-controller[1314]:     self._url("/containers/{0}", container), params=params
Oct 02 09:04:24 agency ccagency-controller[1314]:   File "/home/cc/ccagency-venv/lib/python3.5/site-packages/docker/utils/decorators.py", line 46, in inner
Oct 02 09:04:24 agency ccagency-controller[1314]:     return f(self, *args, **kwargs)
Oct 02 09:04:24 agency ccagency-controller[1314]:   File "/home/cc/ccagency-venv/lib/python3.5/site-packages/docker/api/client.py", line 238, in _delete
Oct 02 09:04:24 agency ccagency-controller[1314]:     return self.delete(url, **self._set_request_timeout(kwargs))
Oct 02 09:04:24 agency ccagency-controller[1314]:   File "/home/cc/ccagency-venv/lib/python3.5/site-packages/requests/sessions.py", line 615, in delete
Oct 02 09:04:24 agency ccagency-controller[1314]:     return self.request('DELETE', url, **kwargs)
Oct 02 09:04:24 agency ccagency-controller[1314]:   File "/home/cc/ccagency-venv/lib/python3.5/site-packages/requests/sessions.py", line 533, in request
Oct 02 09:04:24 agency ccagency-controller[1314]:     resp = self.send(prep, **send_kwargs)
Oct 02 09:04:24 agency ccagency-controller[1314]:   File "/home/cc/ccagency-venv/lib/python3.5/site-packages/requests/sessions.py", line 646, in send
Oct 02 09:04:24 agency ccagency-controller[1314]:     r = adapter.send(request, **kwargs)
Oct 02 09:04:24 agency ccagency-controller[1314]:   File "/home/cc/ccagency-venv/lib/python3.5/site-packages/requests/adapters.py", line 516, in send
Oct 02 09:04:24 agency ccagency-controller[1314]:     raise ConnectionError(e, request=request)
Oct 02 09:04:24 agency ccagency-controller[1314]: requests.exceptions.ConnectionError: HTTPSConnectionPool(host='pepper01.f4.htw-berlin.de', port=2376): Max retries exceeded with url: /v1.40/containers/34595310eae14e1144a9bdecf98033e18f47b7cc073fc311118a535b69329053?force=False&link=
```

**Comment by Bluemi** [comment]
already fixed in 8.1
